project:
  type: website

website:
  google-analytics: "G-FTK61TBF7L"
  title: "Marketing Analytics"
  page-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    background: primary
    contents:
      - syllabus.qmd
      - section: "R Tutorials"
        contents:
          - R-introductionR.qmd
        
format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    number-sections: true
    df-print: paged
    toc-depth: 2

