project:
  type: website

website:
  google-analytics: "G-FTK61TBF7L"
  title: "Marketing Analytics"
  page-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    background: primary
    contents:
      - section: "Lectures"
        contents:
          - syllabus.qmd
          - ClassPreparation.qmd
          - section: "[Week 1] Module Intro and Break-Even Analyses"
            contents: 
              - href: Week1-Lecture1.html
                text: "Class 1 Module Intro"
              - href: Week1-Lecture2.html
                text: "Class 2 Break-Even Analyses"
              - href: Case-BreakEvenAnalysis.html
                text: "Break-Even Analyses for PineApple Inc"
              - href: Case-BreakEvenAnalysis-Solutions.html
                text: "Break-Even Analyses for PineApple Inc (Solutions)"
          - section: "[Week 2] Customer Lifetime Value and Data Wrangling with R"
            contents: 
              - href: Week2-Lecture1.html
                text: "Class 3 Customer Lifetime Value Case Study"
              - href: Week2-Lecture2.html
                text: "Class 4 Data Wrangling with R I"
              - href: Case-CLSV.html
                text: "CLSV Solutions"
          - section: "[Week 3] Unsupervised Learning and Customer Segmentation"
            contents: 
              - href: Week3-Lecture1.html
                text: "Class 5 Data Wrangling with R II "
              - href: Week3-Lecture2.html
                text: "Class 6 Unsupervised Learning"
              - href: Case-PreliminaryCustomerAnalysis-stu.pdf
                text: "Preliminary Customer Analyses"  
              - href: Case-PreliminaryCustomerAnalysis.html
                text: "Case Solution: Descriptive Analytics"  
          - section: "[Week 4] Supervised Learning and Customer Targeting"
            contents: 
              - href: Week4-Lecture1.html
                text: "Class 7 Supervised Learning"
              - href: Week4-Lecture2.html
                text: "Class 8: Improve Marketing Efficiency Using Predictive Analytics"
              - href: Case-PredictiveAnalytics-stu.pdf
                text: "Improving Marketing Efficiency Using Predictive Analytics"  
              - href: Case-PredictiveAnalytics.html
                text: "Case Solution: Predictive Analytics"
          - section: "[Week 5] Causal Inference and RCT"
            contents: 
              - href: Week5-Lecture1.html
                text: "Class 9 Causal Inference"
              - href: Week5-Lecture2.html
                text: "Class 10 Randomized Controlled Trials"
          - section: "[Week 6] Linear Regression Models"
            contents: 
              - href: Week6-Lecture1.html
                text: "Class 11 Application of A-B Testing at Vungle"
              - href: Week6-Lecture2.html
                text: "Class 12 Linear Regression Basics"
          - section: "[Week 7] Marketing Mix Modeling"
            contents: 
              - href: Week7-Lecture1.html
                text: "Class 13 Linear Regression Advanced"
              - href: Week7-Lecture2.html
                text: "Class 14 Marketing Mix Modeling"
              - href: Case-Zalora.html
                text: "Case Solution: Zalora"
          - section: "[Week 8] Endogeneity and Instrumental Variable"
            contents: 
              - href: Week8-Lecture1.html
                text: "Class 15 Endogeneity"
              - href: Week8-Lecture2.html
                text: "Class 16 Instrumental Variable"
              - href: Case-COVID-IV-stu.pdf
                text: "Case: COVID-19 and Ridesharing"  
              - href: Case-COVID-IV.html
                text: "Case Solution: COVID-19 and Ridesharing"
          - section: "[Week 9] Natural Experiment"
            contents: 
              - href: Week9-Lecture1.html
                text: "Class 17 Difference-in-Differences"
              - href: Week9-Lecture2.html
                text: "Class 18 Regression Discontinuity Design"
              
      - section: "R Tutorials"
        contents:
          - R-installR.qmd
          - R-InductionWeek.qmd
          - R-errors.qmd
      - section: "Advanced R Tips"
        contents:
          - RTip-BLAS.qmd
format:
  html:
    theme: lumen
    embed-resources: true
    standalone: true
    css: styles.css
    toc: true
    number-sections: true
    df-print: paged
    toc-depth: 3
execute: 
  freeze: auto

