project:
  type: website

website:
  #google-analytics: "G-FTK61TBF7L"
  title: "Marketing Analytics"
  page-navigation: true
  reader-mode: false
  sidebar:
    style: "docked"
    search: true
    background: primary
    tools: 
      - icon: youtube
        href: https://youtube.com/@MeowMeowAnalytics?si=mBVfkYi4u95f6uxp
    contents:
      - section: "Lectures"
        contents:
          - Syllabus.qmd
          - WeeklyArrangements.qmd
          - section: "[Week 1] Module Introduction and Marketing Profitability Analysis"
            contents: 
              - LectureSlides.qmd
      - section: "R Tutorials"
        contents:
          - R-InstallR.qmd
          - R-RStudioSetup.qmd
          - href: R-Basics.qmd
            text: "R Basics (Induction Week)"
          - href: R-ComparisonWithPython.qmd
            text: "Side-by-Side Comparison between R and Python"
          - R-errors.qmd
      - section: "Advanced R Tips"
        contents:
          - RTip-BLAS.qmd
format:
  html:
    theme:
      light: lumen
      dark: darkly
    toc: true
    toc-depth: 2
    number-sections: true
    lightbox: true
    df-print: paged
    page-layout: full
    code-line-numbers: true
    code-copy: hover
    code-fold: show
    execute:
      echo: true
    embed-resources: true
    standalone: true
    css: styles.css
    fig-align: "center"
  beamer:
    toc: false
    slide-level: 2
    section-titles: true
    theme: Frankfurt
    colortheme: beaver
    fonttheme: structurebold
    navigation: horizontal
    tbl-colwidths: auto
    fontsize: 9pt 
    fig-align: "center"
execute: 
  freeze: auto

