project:
  type: website

website:
  google-analytics: "G-FTK61TBF7L"
  title: "Marketing Analytics"
  page-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    background: primary
    tools: 
      - icon: youtube
        href: https://youtube.com/@MeowMeowAnalytics?si=mBVfkYi4u95f6uxp
    contents:
      - section: "Lectures"
        contents:
          - Syllabus.qmd
          - WeeklyArrangements.qmd
          - section: "[Week 1] Module Introduction and Profitability Analysis"
            contents:
              - href: Week1-Lecture1.qmd
                text: "Lecture 1: Introduction to Marketing Analytics"
              - href: Week1-Lecture2.qmd
                text: "Lecture 2: Marketing Profitability Analysis"
              - href: Case-ProfitabilityAnalysis.qmd
                text: "Case Study: Profitability Analysis for Apple Inc."
          - section: "[Week 2] Customer Lifetime Value"
            contents:
              - href: Week2-Lecture1.qmd
                text: "Lecture 1: Customer Lifetime Value"
              - href: Week2-Lecture2.qmd
                text: "Lecture 2: Case Study: CLV for M&S"
              - href: Case-CLV.qmd
                text: "Case Study: CLV Analysis for M&S's Delivery Pass"
          - section: "[Week 3] Data Wrangling and Descriptive Analytics"
            contents:
              - href: Week3-Lecture1.qmd
                text: "Lecture 1: Data Wrangling with R"
              - href: Week3-Lecture2.qmd
                text: "Lecture 2: Caset Study: Descriptive Analytics for M&S"
              - href: Case-PreliminaryCustomerAnalysis.qmd
                text: "Case Study: Descriptive Analytics for M&S"
          - section: "[Week 4] Unsupervised Learning for Customer Segmentation"
            contents:
              - href: Week4-Lecture1.qmd
                text: "Lecture 1: Unsupervised Learning and K-Means Clustering"
              - href: Week4-Lecture2.qmd
                text: "Lecture 2: Case Study: Customer Segmentation Using K-Means for M&S"
              - href: Case-PredictiveAnalyticsI.qmd
                text: "Case Study: Customer Segmentation Using K-Means for M&S"
          - section: "[Week 5] Supervised Learning for Customer Targeting"
            contents:
              - href: Week5-Lecture1.qmd
                text: "Lecture 1: Supervised Learning and Tree-Based Models"
              - href: Week5-Lecture2.qmd
                text: "Lecture 2: Case Study: Customer Targeting Using Supervised Learning for M&S"
              - href: Case-PredictiveAnalyticsII.qmd
                text: "Case Study: Customer Targeting Using Supervised Learning for M&S"
          - section: "[Week 6] Causal Inference and A/B Testing"
            contents: 
              - href: Week6-Lecture1.qmd
                text: "Lecture 1: Causal Inference and Potential Outcome Framework"
              - href: Week6-Lecture2.qmd
                text: "Lecture 2: A/B Testing"
          - section: "[Week 7] Linear Regression Models"
            contents:
              - href: Week7-Lecture1.qmd
                text: "Lecture 1: Improve User Engagement for Instagram Using A/B/N Testing"
              - href: Week7-Lecture2.qmd
                text: "Lecture 2: Linear Regression for Causal Inference"
              - href: Case-CausalInference.qmd
                text: "Case Study: Improve User Engagement for Instagram Using A/B/N Testing"
          - section: "[Week 8] Endogeneity and Instrumental Variables"
            contents:
              - href: Week8-Lecture1.qmd
                text: "Lecture 1: Endogeneity"
              - href: Week8-Lecture2.qmd
                text: "Lecture 2: Instrumental Variables and Two-Stage Least Squares"
          - section: "[Week 9] Natural Experiment"
            contents:
              - href: Week9-Lecture1.qmd
                text: "Lecture 1: Case Study: Estimating Causal Effects for Platform Businesses Using Instrumental Variables"
              - href: Week9-Lecture2.qmd
                text: "Lecture 2: Natural Experiment I: Regression Discontinuity Design"
              - href: Case-IV.qmd
                text: "Case Study: Case Study: Estimating Causal Effects for Platform Businesses Using Instrumental Variables"
          - section: "[Week 10] Frontiers of Marketing Analytics"
            contents:
              - href: Week10-Lecture1.qmd
                text: "Lecture 1: Natural Experiment II: Difference-in-Differences"
              - href: Week10-Lecture2.qmd
                text: "Lecture 2: Looking Back & Moving Forward"
          - R-Exercise.qmd
      - section: "R Tutorials"
        contents:
          - R-InstallR.qmd
          - R-RStudioSetup.qmd
          - href: R-Basics.qmd
            text: "R Basics (Induction Week)"
          - href: R-ComparisonWithPython.qmd
            text: "Side-by-Side Comparison between R and Python"
          - R-errors.qmd
          - R-Exercise.qmd
      - section: "Advanced R Tips"
        contents:
          - RTip-BLAS.qmd
format:
  html:
    author: "Dr Wei Miao"
    institute: "UCL School of Management"
    date-format: long
    theme:
      light: lumen
      dark: darkly
    toc: true
    toc-depth: 2
    tabsets: true
    number-sections: true
    lightbox: true
    df-print: paged
    page-layout: full
    code-line-numbers: true
    code-copy: hover
    code-fold: show
    execute:
      echo: true
    embed-resources: true
    standalone: true
    css: styles.css
    fig-align: "center"
    colorlinks: true
    code-tools: true
    bibliography: references.bib
  beamer:
    author: "Dr. Wei Miao"
    institute: "UCL School of Management"
    date-format: long
    toc: false
    slide-level: 2
    section-titles: true
    theme: Frankfurt
    colortheme: beaver
    fonttheme: structurebold
    navigation: horizontal
    tbl-colwidths: auto
    fontsize: 9pt 
    fig-align: "center"
    colorlinks: true
    bibliography: references.bib
    supress-bibliography: true
    execute:
      error: true
knitr:
  opts_chunk: 
    out.width: "5cm"
    fig.align: "center"
execute: 
  freeze: auto
  cache: false