project:
  type: website

website:
  google-analytics: "G-FTK61TBF7L"
  title: "Marketing Analytics"
  page-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    background: primary
    contents:
      - section: "Lectures"
        contents:
          - syllabus.qmd
          - ClassPreparation.qmd
          - LectureSlides.qmd
          - R-InductionWeek.qmd
      - section: "R Tutorials"
        contents:
          - R-installR.qmd
          - R-introductionR.qmd
          - R-errors.qmd
      - section: "Advanced R Tips"
        contents:
          - RTip-BLAS.qmd
      
format:
  html:
    theme: lumen
    self-contained: true
    self-contained-math: true
    css: styles.css
    toc: true
    number-sections: true
    df-print: paged
    toc-depth: 3

