project:
  type: website

website:
  google-analytics: "G-FTK61TBF7L"
  title: "Marketing Analytics"
  page-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    background: primary
    contents:
      - section: "Lectures"
        contents:
          - syllabus.qmd
          - ClassPreparation.qmd
          - section: "[Week 1] Marketing Process and Break-Even Analyses"
            contents: 
              - href: Week1-Lecture1.html
                text: "Class 1 Intro to Marketing (HTML)"
              - href: Week1-Lecture1.pdf
                text: "Class 1 Intro to Marketing (PDF)"
              - href: Week1-Lecture2.html
                text: "Class 2 Break-Even Analyses (HTML)"
              - href: Week1-Lecture2.pdf
                text: "Class 2 Break-Even Analyses (PDF)"
              - href: Case-BreakEvenAnalysis.html
                text: "Break-Even Analyses for PineApple Inc (HTML)"
              - href: Case-BreakEvenAnalysis.pdf
                text: "Break-Even Analyses for PineApple Inc (PDF)"
              - href: ClassExercise.html
                text: "In-Class Exercise Solutions"
          - section: "[Week 2] Customer Lifetime Value and Data Wrangling with R"
            contents: 
              - href: Week2-Lecture1.html
                text: "Class 3 Customer Lifetime Value Case Study (HTML)"
              - href: Week2-Lecture1.pdf
                text: "Class 3 Customer Lifetime Value Case Study (PDF)"
              - href: Week2-Lecture2.html
                text: "Class 4 Data Wrangling with R I (HTML)"
              - href: Week2-Lecture2.pdf
                text: "Class 4 Data Wrangling with R I (PDF)"
              - href: CLSV-Case.html
                text: "CLSV Solutions"
          - section: "[Week 3] Unsupervised Learning and Customer Segmentation"
            contents: 
              - href: Week3-Lecture1.html
                text: "Class 5 Data Wrangling with R II  (HTML)"
              - href: Week3-Lecture1.pdf
                text: "Class 5 Data Wrangling with R II (PDF)"
              - href: Week3-Lecture2.html
                text: "Class 6 Clustering for Customer Segmentation (HTML)"
              - href: Week3-Lecture2.pdf
                text: "Class 6 Clustering for Customer Segmentation (PDF)"
              - href: Case-PreliminaryCustomerAnalysis-stu.pdf
                text: "Preliminary Customer Analyses"  
      - section: "R Tutorials"
        contents:
          - R-installR.qmd
          - section: "R Basics Part I (Induction Week)"
            contents: 
              - R-InductionWeek.qmd
              - href: R-InductionWeek.pdf
                text: "pdf version"
          - section: "R Basics Part II (Induction Week)"
            contents: 
              - R-InductionWeek-II.qmd
              - href: R-InductionWeek-II.pdf
                text: "pdf version"
          - R-errors.qmd
      - section: "Advanced R Tips"
        contents:
          - RTip-BLAS.qmd
format:
  html:
    theme: lumen
    embed-resources: true
    standalone: true
    css: styles.css
    toc: true
    number-sections: true
    df-print: paged
    toc-depth: 3
execute: 
  freeze: auto

