project:
  type: website

website:
  google-analytics: "G-FTK61TBF7L"
  title: "Marketing Analytics"
  page-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    background: primary
    tools: 
      - icon: youtube
        href: https://youtube.com/@MeowMeowAnalytics?si=mBVfkYi4u95f6uxp
    contents:
      - section: "Lectures"
        contents:
          - Syllabus.qmd
          - WeeklyArrangements.qmd
          - section: "[Week 1] Module Introduction and Profitability Analysis"
            contents:
              - href: Week1-Lecture1.qmd
                text: "Lecture 1: Introduction to Marketing Analytics"
              - href: Week1-Lecture2.qmd
                text: "Lecture 2: Marketing Profitability Analysis"
              - href: Case-ProfitabilityAnalysis.qmd
                text: "Case Study: Profitability Analysisfor Apple Inc."
          - section: "[Week 2] Customer Lifetime Value"
            contents:
              - LectureSlides.qmd
          - R-Exercise.qmd
      - section: "R Tutorials"
        contents:
          - R-InstallR.qmd
          - R-RStudioSetup.qmd
          - href: R-Basics.qmd
            text: "R Basics (Induction Week)"
          - href: R-ComparisonWithPython.qmd
            text: "Side-by-Side Comparison between R and Python"
          - R-errors.qmd
          - R-Exercise.qmd
      - section: "Advanced R Tips"
        contents:
          - RTip-BLAS.qmd
format:
  html:
    theme:
      light: lumen
      dark: darkly
    toc: true
    toc-depth: 2
    tabsets: true
    number-sections: true
    lightbox: true
    df-print: paged
    page-layout: full
    code-line-numbers: true
    code-copy: hover
    code-fold: show
    execute:
      echo: true
    embed-resources: true
    standalone: true
    css: styles.css
    fig-align: "center"
    colorlinks: true
  beamer:
    toc: false
    slide-level: 2
    section-titles: true
    theme: Frankfurt
    colortheme: beaver
    fonttheme: structurebold
    navigation: horizontal
    tbl-colwidths: auto
    fontsize: 9pt 
    fig-align: "center"
    colorlinks: true
knitr:
  opts_chunk: 
    out.width: "5cm"
    fig.align: "center"
execute: 
  freeze: auto
  cache: false