project:
  type: website

website:
  google-analytics: "G-FTK61TBF7L"
  title: "Marketing Analytics"
  page-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    background: primary
    contents:
      - section: "Lectures"
        contents:
          - syllabus.qmd
          - ClassPreparation.qmd
          - section: "[Week 1] Marketing Process and Break-Even Analyses"
            contents: 
              - href: Week1-Lecture1.html
                text: "Class 1 Intro to Marketing (HTML)"
              - href: Week1-Lecture1.pdf
                text: "Class 1 Intro to Marketing (PDF)"
              - href: Week1-Lecture2.html
                text: "Class 2 Break-Even Analyses (HTML)"
              - href: Week1-Lecture2.pdf
                text: "Class 2 Break-Even Analyses (PDF)"
              - href: Case-BreakEvenAnalysis.html
                text: "Break-Even Analyses for PineApple Inc (HTML)"
              - href: Case-BreakEvenAnalysis.pdf
                text: "Break-Even Analyses for PineApple Inc (PDF)"
              - href: ClassExercise.html
                text: "In-Class Exercise Solutions"
          - section: "[Week 2] Customer Lifetime Value and Data Wrangling with R"
            contents: 
              - href: Week2-Lecture1.html
                text: "Class 3 Customer Lifetime Value Case Study (HTML)"
              - href: Week2-Lecture1.pdf
                text: "Class 3 Customer Lifetime Value Case Study (PDF)"
              - href: Week2-Lecture2.html
                text: "Class 4 Data Wrangling with R I (HTML)"
              - href: Week2-Lecture2.pdf
                text: "Class 4 Data Wrangling with R I (PDF)"
              - href: CLSV-Case.html
                text: "CLSV Solutions"
          - section: "[Week 3] Unsupervised Learning and Customer Segmentation"
            contents: 
              - href: Week3-Lecture1.html
                text: "Class 5 Data Wrangling with R II  (HTML)"
              - href: Week3-Lecture1.pdf
                text: "Class 5 Data Wrangling with R II (PDF)"
              - href: Week3-Lecture2.html
                text: "Class 6 Unsupervised Learning (HTML)"
              - href: Week3-Lecture2.pdf
                text: "Class 6 Unsupervised Learning (PDF)"
              - href: Case-PreliminaryCustomerAnalysis-stu.pdf
                text: "Preliminary Customer Analyses"  
              - href: Case-PreliminaryCustomerAnalysis.html
                text: "Case Solution"  
          - section: "[Week 4] Supervised Learning and Customer Targeting"
            contents: 
              - href: Week4-Lecture1.html
                text: "Class 7 Supervised Learning (html)"
              - href: Week4-Lecture1.pdf
                text: "Class 7 Supervised Learning (PDF)"
              - href: Week4-Lecture2.html
                text: "Class 8: Improve Marketing Efficiency Using Predictive Analytics (HTML)"
              - href: Week4-Lecture2.pdf
                text: "Class 8: Improve Marketing Efficiency Using Predictive Analytics (PDF)"
              - href: Case-PredictiveAnalytics-stu.pdf
                text: "Improving Marketing Efficiency Using Predictive Analytics"  
              - href: Case-PredictiveAnalytics.html
                text: "Case Solution: Predictive Analytics"
          - section: "[Week 5] Causal Inference and RCT"
            contents: 
              - href: Week5-Lecture1.html
                text: "Class 9 Causal Inference (html)"
              - href: Week5-Lecture1.pdf
                text: "Class 9 Causal Inference (PDF)"
              - href: Week5-Lecture2.html
                text: "Class 10 Randomized Controlled Trials (HTML)"
              - href: Week5-Lecture2.pdf
                text: "Class 10 Randomized Controlled Trials (PDF)"
          - section: "[Week 6] Linear Regression Models"
            contents: 
              - href: Week6-Lecture1.html
                text: "Class 11 Application of A-B Testing at Vungle (html)"
              - href: Week6-Lecture1.pdf
                text: "Class 11 Application of A-B Testing at Vungle (PDF)"
              - href: Week6-Lecture2.html
                text: "Class 12 Linear Regression Basics (HTML)"
              - href: Week6-Lecture2.pdf
                text: "Class 12 Linear Regression Basics (PDF)"
          - section: "[Week 7] Marketing Mix Modeling"
            contents: 
              - href: Week7-Lecture1.html
                text: "Class 13 Linear Regression Advanced (HTML)"
              - href: Week7-Lecture1.pdf
                text: "Class 13 Linear Regression Advanced (PDF)"
              - href: Week7-Lecture2.html
                text: "Class 14 Marketing Mix Modeling (HTML)"
              - href: Week7-Lecture2.pdf
                text: "Class 14 Marketing Mix Modeling (PDF)"
              - href: Case-Zalora.html
                text: "Case Solution: Zalora"
      - section: "R Tutorials"
        contents:
          - R-installR.qmd
          - section: "R Basics Part I (Induction Week)"
            contents: 
              - R-InductionWeek.qmd
              - href: R-InductionWeek.pdf
                text: "pdf version"
          - section: "R Basics Part II (Induction Week)"
            contents: 
              - R-InductionWeek-II.qmd
              - href: R-InductionWeek-II.pdf
                text: "pdf version"
          - R-errors.qmd
      - section: "Advanced R Tips"
        contents:
          - RTip-BLAS.qmd
format:
  html:
    theme: lumen
    embed-resources: true
    standalone: true
    css: styles.css
    toc: true
    number-sections: true
    df-print: paged
    toc-depth: 3
execute: 
  freeze: auto

