---
title: "Syllabus"
date: "2024-09-17"
date-modified: "2024-09-22"
date-format: long
---

# Instructor Information

-   Module leader: Dr. Wei Miao [[personal website](https://miaowei.netlify.app/)]

-   Email: [wei.miao\@ucl.ac.uk](mailto:wei.miao@ucl.ac.uk)

-   Teaching assistants

    -   Kayi Yeung, [ka.yeung.21\@ucl.ac.uk](mailto:ka.yeung.21@ucl.ac.uk) (UCL MSc BA 2022)
    -   Jiafan Lu, [jiafan.lu\@ucl.ac.uk](mailto:jiafan.lu.22@ucl.ac.uk) (UCL PhD Management 2022)

# Course Objective

Marketing analytics addresses how to utilize the right analytics tools to guide marketing tactics and strategies in a scientific manner. Driven by recent advances in information and communication technologies, the very nature of marketing analytics has evolved. This module provides students with systematic and practical training in R programming, machine learning, and causal inference tools to solve real-life marketing problems[^1].

[^1]: Just a little heads up \-- unlike undergrad marketing modules where you mainly learn marketing strategies and concepts, this module focuses on "analytics" (which comes first) and its application in "marketing" (which comes next). So, be prepared to learn a lot of data wrangling, machine learning, and causal inference tools in this module.

In the first 2 weeks, students will learn the principles of marketing and how to conduct profitability analyses, including break-even quantity, net present value, and customer lifetime value, for guiding marketing activities. Starting in week 3, students will gradually acquire data wrangling skills with R and learn how to apply these skills in descriptive analytics.

In week 4 and week 5, students will learn predictive analytics and how to apply machine learning models for segmentation, targeting, and customer relationship management.

In the remaining weeks, students will learn causal inference tools, which help marketers correctly measure the causal effects of marketing initiatives on marketing outcomes. Students will get hands-on training in A/B testing, linear regression, instrumental variable method, natural experiments, and causal machine learning.

The course uses a combination of lectures, cases, and exercises to achieve the best learning outcomes. This course takes a very hands-on approach with real-world databases and equips students with tools that can be used immediately on the job. At the end of the module, students will be able to carry out independent marketing research for their dissertation projects and their future jobs.

# Course Structure (tentative)

Please refer to the [weekly arrangements](WeeklyArrangements.qmd) for the detailed course structure, learning objectives, and preparation required each week. Note that the topics are tentative and are subject to adjustments depending on our learning progress.

# Office Hours

## If you have questions about the lecture, first check the Teams channel

We will use Microsoft Teams for the module. Please utilize the Microsoft Teams Q&A channels as an interactive place for peer learning.

Since some of your questions may have been asked by your peers, for any questions, please first check the MS Teams channel and see if the questions are already posted and answered there. If not, please post your questions in the Teams channels. The teaching team will monitor the questions posted on Teams and provide answers accordingly.

## If you have questions about the assignments, make an appointment

You can also ask questions during office hours hosted by me or teaching assistants during term time. 

To make an appointment, use the link below. The links are also available under "Module Overview" Section on Moodle. Note that you need to log in with your UCL email account to make an appointment.

- For lecture-related questions, please make an appointment with Wei [here](https://outlook.office365.com/owa/calendar/MarketingAnalyticsOfficeHoursWei@live.ucl.ac.uk/bookings/s/mfjnYXzzTk6c_1gb5Gx3Sw2).

- For R trouble-shooting, please make an appointment with teaching assistants [here](https://outlook.office365.com/owa/calendar/MarketingAnalyticsOfficeHoursWei@live.ucl.ac.uk/bookings/s/Fr4etO85jEWCU7to5RXDhw2)

# Textbook

Since the marketing field is evolving rapidly, we aim to cover the latest marketing analytics techniques; therefore, we will not rely on any specific textbook in this module. All classes will be based on the lecture notes and supplementary readings I have prepared for you.

Nevertheless, if you would like to further enrich your learning journey and extend your knowledge of marketing analytics, I recommend

-   ["Handbook of Marketing Analytics"](https://ucl-new-primo.hosted.exlibrisgroup.com/permalink/f/5qfvbu/UCL_LMS_DS51237610180004761). This book is free for download at UCL's E-library.

-   ["Introduction to Econometrics with R"](https://www.econometrics-with-r.org/index.html), which is a good textbook for learning econometrics with R.

# Programming with R

We will use an open-source programming language R throughout the module. R is one of the most commonly used programming languages by data scientists, economists, and statisticians, and is sometimes called the "golden child" of data science. R is cross-platform compatible on Windows, Mac, and Linux, with thousands of packages ready for use. Undoubtedly, it has one of the richest ecosystems to perform data analytics tasks. More importantly, it is free of charge compared with other commercial software!

- If you have little prior exposure to R before joining MSc Business Analytics, it is highly advised that you should self-study this tutorial, ["Introduction to R"](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf).

- Make sure you have installed R, RStudio, and Quarto following this [guide](https://weim-mkt.github.io/UCLMarketingAnalytics/R-InstallR.html) before attending the induction week's tutorial on Friday.

# Assignments and Grading policy

There will be no exams in this module. Learning outcomes will be examined through three individual assignments. Your final grade in this module will be a weighted average of the following:

-   First assignment: 30% weight, 1500 words, due Friday, 25 October 2024
-   Second assignment: 30% weight, 1500 words, due Friday, 15 November 2024
-   Third assignment: 40% weight, 2000 words, due Friday, 13 December 2024

Detailed assignment descriptions will be given in due course.

-   **Academic integrity**: You will receive training in Student Academic Misconduct Procedure in the induction week, in which you will learn how to properly reference your work and avoid plagiarism. As all assignments in this module are individual assignments, you should NOT work with other students in any way. Note that it will be a severe violation of academic integrity if you look for solutions on the Internet or even outsource the assignments to any agency. You may risk failing this module if such a violation is found and investigated by the University.

-   **Word count**: You should follow the word limit. Otherwise, your marks may be reduced. Therefore, try to keep your answer concise and to the point.

-   **Submission** Please double check (or even triple check) whether the file to be uploaded is the correct, finalized answer sheet before submission. The final marks will be ONLY based on the file you submit, even though you may be able to show evidence that a wrong file is uploaded.

-   **Assistance with submission**: Neither I nor the TAs are authorized to handle ECs or any emergencies related to assignment submission. Please directly contact the MSc program admin [here](mailto:%20mgmt.ba-admin@ucl.ac.uk) for any assistance.

# Copyright

All of the materials in this module are copyrighted, either purchased by UCL or written by me. Please refrain from uploading any materials (including uploading assignments to unauthorized websites for answers) in the module to other external websites or sharing any materials with anyone unauthorized. A copyright violation may be investigated by the school.
